# Generated by Django 5.0.6 on 2024-05-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_question_quiz_answer_question_quiz"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Image",
            new_name="Person",
        ),
    ]
