# Generated by Django 5.0.6 on 2024-05-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_rename_image_person"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"verbose_name_plural": "People"},
        ),
    ]
